# Overrides for prod environment
# Usage: helm upgrade --install infra-api ./helm/infra-api -f values-prod.yaml

replicaCount: 2

image:
  tag: "" # set at deploy time via --set image.tag=<sha>

env:
  APP_ENV: prod
  PORT: "5050"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

namespace: prod
