apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shanecthomas/gitops-helm-argocd-demo.git
    targetRevision: main
    path: gitops/helm/infra-api
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: "$IMAGE_TAG" # substituted by the workflow before apply
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
